<?php

namespace Asgard\Bundle\PlannerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CapacityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapacityRepository extends EntityRepository
{
}
