admin_game:
    pattern:  /
    defaults: { _controller: "AsgardPlannerBundle:Game:index" }

admin_game_show:
    pattern:  /{id}/show
    defaults: { _controller: "AsgardPlannerBundle:Game:show" }

admin_game_new:
    pattern:  /new
    defaults: { _controller: "AsgardPlannerBundle:Game:new" }

admin_game_create:
    pattern:  /create
    defaults: { _controller: "AsgardPlannerBundle:Game:create" }
    requirements: { _method: post }

admin_game_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AsgardPlannerBundle:Game:edit" }

admin_game_update:
    pattern:  /{id}/update
    defaults: { _controller: "AsgardPlannerBundle:Game:update" }
    requirements: { _method: post }

admin_game_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AsgardPlannerBundle:Game:delete" }
    requirements: { _method: post }
