Asgard\Bundle\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Asgard\Bundle\UserBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
