Asgard\Bundle\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Asgard\Bundle\UserBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        players:
            targetEntity: Asgard\Bundle\PlannerBundle\Entity\Player
            mappedBy: user
        messages:
            targetEntity: Asgard\Bundle\PlannerBundle\Entity\Message
            mappedBy: user
    lifecycleCallbacks: {  }
