Asgard\Bundle\PlannerBundle\Entity\Classification:
    type: entity
    table: null
    repositoryClass: Asgard\Bundle\PlannerBundle\Entity\ClassificationRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    oneToMany:
        players:
            targetEntity: Player
            mappedBy: classification
    manyToMany:
        races:
            targetEntity: Race
    manyToOne:
        game:
            targetEntity: Game
    lifecycleCallbacks: {  }
