Asgard\Bundle\PlannerBundle\Entity\Location:
    type: entity
    table: null
    repositoryClass: Asgard\Bundle\PlannerBundle\Entity\LocationRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    manyToOne:
        game:
            targetEntity: Game
            inversedBy: locations
    manyToMany:
        capacities:
            targetEntity: Capacity
        modes:
            targetEntity: Mode
    oneToMany:
        events:
            targetEntity: Event
            mappedBy: location
    lifecycleCallbacks: {  }
