Asgard\Bundle\PlannerBundle\Entity\Participation:
    type: entity
    table: null
    repositoryClass: Asgard\Bundle\PlannerBundle\Entity\ParticipationRepository
    id:
        event:
            associationKey: true
        player:
            associationKey: true
    fields:
        retained:
            type: boolean
        missing:
            type: boolean
    manyToOne:
        event:
            targetEntity: Event
            inversedBy: participations
        player:
            targetEntity: Player
            inversedBy: participations
        role:
            targetEntity: Role
            inversedBy: participations
    lifecycleCallbacks: {  }
