Asgard\Bundle\PlannerBundle\Entity\Player:
    type: entity
    table: null
    repositoryClass: Asgard\Bundle\PlannerBundle\Entity\PlayerRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    manyToOne:
        game:
            targetEntity: Game
        user:
            targetEntity: Asgard\Bundle\UserBundle\Entity\User
        race:
            targetEntity: Race
        classification:
            targetEntity: Classification
    manyToMany:
        roles:
            targetEntity: Role
    lifecycleCallbacks: {  }
