Asgard\Bundle\PlannerBundle\Entity\Player:
    type: entity
    table: null
    repositoryClass: Asgard\Bundle\PlannerBundle\Entity\PlayerRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    manyToOne:
        game:
            targetEntity: Game
            inversedBy: players
        user:
            targetEntity: Asgard\Bundle\UserBundle\Entity\User
            inversedBy: players
        race:
            targetEntity: Race
            inversedBy: players
        classification:
            targetEntity: Classification
            inversedBy: players
    manyToMany:
        roles:
            targetEntity: Role
    oneToMany:
        participations:
            targetEntity: Participation
            mappedBy: player
    lifecycleCallbacks: {  }
