Asgard\Bundle\PlannerBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: Asgard\Bundle\PlannerBundle\Entity\RoleRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    manyToMany:
        players:
            targetEntity: Player
        games:
            targetEntity: Game
    oneToMany:
        needs:
            targetEntity: EventNeed
            mappedBy: role
        participations:
            targetEntity: Participation
            mappedBy: role
    lifecycleCallbacks: {  }
